<a href="https://colab.research.google.com/github/komalprashar790-cmyk/Machine-Learning-model/blob/main/englishtohindi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
data = pd.read_csv("/content/english_hindi_50000_rows.csv")
print(data.head())

   id       english         hindi     data_type  variant_group
0   1         Hello        नमस्ते  seed_example              0
1   2  Good morning      सुप्रभात  seed_example              0
2   3  Good evening    शुभ संध्या  seed_example              0
3   4  How are you?  आप कैसे हैं?  seed_example              0
4   5    I am fine.  मैं ठीक हूँ।  seed_example              0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             50000 non-null  int64
 1   english        50000 non-null  object
 2   hindi          50000 non-null  object
 3   data_type      50000 non-null  object
 4   variant_group  50000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 1.9+ MB

In [8]:
data.describe()

                 id  variant_group
count  50000.000000   50000.000000
mean   25000.500000      14.655000
std    14433.901067       8.749143
min        1.000000       0.000000
25%    12500.750000       7.000000
50%    25000.500000      15.000000
75%    37500.250000      22.000000
max    50000.000000      30.000000

In [9]:
print(data.duplicated().sum)

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool>

In [10]:
data.isnull().sum()

id               0
english          0
hindi            0
data_type        0
variant_group    0
dtype: int64

In [12]:
data.shape

(50000, 5)

In [14]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


# Keep only the English and Hindi columns
data = data[['english', 'hindi']].copy()

# Remove missing values
data = data.dropna(subset=['english', 'hindi'])

# Remove extra spaces
data['english'] = data['english'].astype(str).str.strip()
data['hindi'] = data['hindi'].astype(str).str.strip()

# Remove empty sentences
data = data[(data['english'] != '') & (data['hindi'] != '')]

print("Dataset shape:", data.shape)
data.head()

Dataset shape: (50000, 2)

        english         hindi
0         Hello        नमस्ते
1  Good morning      सुप्रभात
2  Good evening    शुभ संध्या
3  How are you?  आप कैसे हैं?
4    I am fine.  मैं ठीक हूँ।

Create training and testing set

In [17]:
train_data, test_data = train_test_split(data,test_size = 0.2,random_state=30)
print("training_dataset",len(train_data))
print("testing_dataset",len(test_data))

training_dataset 40000
testing_dataset 10000

 Tokenize English

In [18]:
english_tokenizer = Tokenizer(
    filters='',
    oov_token='<OOV>'
)

english_tokenizer.fit_on_texts(train_data['english'])

X_train = english_tokenizer.texts_to_sequences(
    train_data['english']
)

X_test = english_tokenizer.texts_to_sequences(
    test_data['english']
)

print("English vocabulary size:",
      len(english_tokenizer.word_index) + 1)

English vocabulary size: 166

Tokenize HIndi

In [20]:
hindi_tokenizer = Tokenizer(
    filters='',
    oov_token='<OOV>'
)

hindi_tokenizer.fit_on_texts(train_data['hindi'])

y_train = hindi_tokenizer.texts_to_sequences(
    train_data['hindi']
)

y_test = hindi_tokenizer.texts_to_sequences(
    test_data['hindi']
)

print("Hindi vocabulary size:",
      len(hindi_tokenizer.word_index) + 1)

Hindi vocabulary size: 166